service:
  name: passbook
environment: local

server:
  port: 8080

mongo-db:
  name: passbook

spring:
  data:
    mongodb:
      uri: mongodb+srv://ravibala-13:bals1999@cluster0.hfo0i.mongodb.net/?retryWrites=true&w=majority
      database: passbook